"""Internal utilities for the Pyvider CLI tool."""

import datetime
import pathlib
import subprocess

import click

from pyvider.cli.context import PyviderContext


def _run_command(
    command: list[str] | str,
    cwd: str | None = None,
            env: dict[str, str] | None = None,
    check: bool = True,
    title: str = "",
) -> str:
    cmd_str = " ".join(command)
    effective_cwd = cwd or pathlib.Path.cwd()

    log_dir = pathlib.Path.home() / ".pyvider" / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_file_path = log_dir / "prep.log"

    timestamp = datetime.datetime.now().isoformat()
    log_entry_header = f"--- Log Entry: {timestamp} ---\n"
    log_entry_cmd = f"Command: {cmd_str}\n"
    log_entry_cwd = f"CWD: {effective_cwd}\n"

    step_title = title or cmd_str
    click.secho(f"⏳ {step_title}...", fg="cyan", nl=False)

    try:
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=effective_cwd,
            env=env,
        )
        stdout_str, stderr_str = process.communicate()
        return_code = process.returncode

        with log_file_path.open("a", encoding="utf-8") as f:
            f.write(log_entry_header)
            f.write(log_entry_cmd)
            f.write(log_entry_cwd)
            f.write(f"STDOUT:\n{stdout_str}\n")
            f.write(f"STDERR:\n{stderr_str}\n")
            f.write(f"Return Code: {return_code}\n---\n\n")

        if check and return_code != 0:
            click.secho(" ❌ FAILED", fg="red")
            error_message = f"Command failed with exit code {return_code}. Details in {log_file_path}"
            click.secho(error_message, fg="red")
            raise subprocess.CalledProcessError(
                return_code, command, output=stdout_str, stderr=stderr_str
            )
        else:
            click.secho(" ✅ Done", fg="green")
        return stdout_str

    except subprocess.CalledProcessError:
        raise
    except Exception as e:
        click.secho(" ❌ ERROR", fg="red")
        error_message = (
            f"Failed to run command '{cmd_str}': {e}. Details may be in {log_file_path}"
        )
        click.secho(error_message, fg="red")
        raise


def _place_terraform_provider_script(ctx: PyviderContext) -> None:
    """
    Generates and places a simple Terraform provider wrapper script.
    """
    try:
        if not ctx.tf_plugin_dir.exists():
            ctx.tf_plugin_dir.mkdir(parents=True, exist_ok=True)

        target_provider_path = ctx.tf_plugin_dir / "terraform-provider-pyvider"

        install_dir = pathlib.Path.cwd()

        script_content = f"""#!/bin/bash
# Pyvider Terraform Provider Wrapper Script (Development Mode)
# This script is auto-generated by 'pyvider install'
set -eo pipefail
# set -x
# exec 2> pyvider_provider_debug.log

# The directory where 'pyvider install' was run.
INSTALL_DIR=\"{install_dir}\"

# Determine OS and architecture for platform-specific venv directories
TFOS=$(uname -s | tr '[:upper:]' '[:lower:]')
TFARCH=$(uname -m)
case "$TFARCH" in
    x86_64) TFARCH=\"amd64\";;
    aarch64) TFARCH=\"arm64\";;
    arm64) TFARCH=\"arm64\";;
esac
VENV_NAME=\".venv_${{TFOS}}_${{TFARCH}}\"
VENV_PATH="${{INSTALL_DIR}}/${{VENV_NAME}}/bin/activate"

# --- 1. Change to the installation directory ---
cd "${{INSTALL_DIR}}" || {{ echo \"ERROR: Failed to cd to ${{INSTALL_DIR}}\"; exit 1; }}

# --- 2. Activate Virtual Environment ---
if [ ! -f "${{VENV_PATH}}" ]; then
  echo \"ERROR: Virtual environment not found at '${{VENV_PATH}}'.\" >&2
  echo \"Please run 'uv venv' in \"{install_dir}\".\" >&2
  exit 1
fi
source "${{VENV_PATH}}"

# --- 3. Set PLUGIN_MAGIC_COOKIE_VALUE from TF_PLUGIN_MAGIC_COOKIE environment variable ---
export PLUGIN_MAGIC_COOKIE_VALUE="$TF_PLUGIN_MAGIC_COOKIE"

# --- 4. Execute Provider ---
exec pyvider "$@"
"""

        target_provider_path.write_text(script_content)
        target_provider_path.chmod(target_provider_path.stat().st_mode | 0o111)

    except Exception as e:
        click.secho(
            f"An unexpected error occurred placing provider script: {e}",
            fg="red",
            bold=True,
        )
        raise
