"""Internal utilities for the Pyvider CLI tool."""

import datetime
from pathlib import Path

import click
from provide.foundation.console import pout
from provide.foundation.file import ensure_dir, atomic_write_text
from provide.foundation.process import run_command
from provide.foundation.utils import timed_block

from pyvider.cli.context import PyviderContext


def _run_command(
    command: list[str] | str,
    cwd: str | None = None,
            env: dict[str, str] | None = None,
    check: bool = True,
    title: str = "",
) -> str:
    cmd_str = " ".join(command)
    effective_cwd = cwd or Path.cwd()

    log_dir = Path.home() / ".pyvider" / "logs"
    ensure_dir(log_dir)  # Foundation's safe directory creation
    log_file_path = log_dir / "prep.log"

    timestamp = datetime.datetime.now().isoformat()
    log_entry_header = f"--- Log Entry: {timestamp} ---\n"
    log_entry_cmd = f"Command: {cmd_str}\n"
    log_entry_cwd = f"CWD: {effective_cwd}\n"

    step_title = title or cmd_str
    pout(f"⏳ {step_title}...", style="cyan", end="")

    try:
        with timed_block() as timer:
            # Use foundation's process runner with better error handling
            result = run_command(
                command,
                cwd=effective_cwd,
                env=env,
                check=False  # We handle return codes ourselves
            )
        stdout_str, stderr_str = result.stdout, result.stderr
        return_code = result.returncode

        # Use foundation's safe file operations for atomic logging
        log_content = (
            f"{log_entry_header}"
            f"{log_entry_cmd}"
            f"{log_entry_cwd}"
            f"Duration: {timer.elapsed:.2f}s\n"
            f"STDOUT:\n{stdout_str}\n"
            f"STDERR:\n{stderr_str}\n"
            f"Return Code: {return_code}\n---\n\n"
        )
        
        # Append to existing log file safely
        existing_content = ""
        if log_file_path.exists():
            existing_content = log_file_path.read_text(encoding="utf-8")
        
        atomic_write_text(log_file_path, existing_content + log_content)

        if check and return_code != 0:
            pout(" ❌ FAILED", style="red")
            error_message = f"Command failed with exit code {return_code}. Details in {log_file_path}"
            pout(error_message, style="red")
            from provide.foundation.process import ProcessError
            raise ProcessError(
                f"Command failed with exit code {return_code}",
                exit_code=return_code,
                command=command,
                stdout=stdout_str,
                stderr=stderr_str
            )
        else:
            pout(f" ✅ Done ({timer.elapsed:.2f}s)", style="green")
        return stdout_str

    except Exception as e:
        pout(" ❌ ERROR", style="red")
        error_message = (
            f"Failed to run command '{cmd_str}': {e}. Details may be in {log_file_path}"
        )
        pout(error_message, style="red")
        raise


def _place_terraform_provider_script(ctx: PyviderContext) -> None:
    """
    Generates and places a simple Terraform provider wrapper script.
    """
    try:
        if not ctx.tf_plugin_dir.exists():
            ctx.tf_plugin_dir.mkdir(parents=True, exist_ok=True)

        target_provider_path = ctx.tf_plugin_dir / "terraform-provider-pyvider"

        install_dir = Path.cwd()

        script_content = f"""#!/bin/bash
# Pyvider Terraform Provider Wrapper Script (Development Mode)
# This script is auto-generated by 'pyvider install'
set -eo pipefail
# set -x
# exec 2> pyvider_provider_debug.log

# The directory where 'pyvider install' was run.
INSTALL_DIR=\"{install_dir}\"

# Determine OS and architecture for platform-specific venv directories
TFOS=$(uname -s | tr '[:upper:]' '[:lower:]')
TFARCH=$(uname -m)
case "$TFARCH" in
    x86_64) TFARCH=\"amd64\";;
    aarch64) TFARCH=\"arm64\";;
    arm64) TFARCH=\"arm64\";;
esac
VENV_NAME=\".venv_${{TFOS}}_${{TFARCH}}\"
VENV_PATH="${{INSTALL_DIR}}/${{VENV_NAME}}/bin/activate"

# --- 1. Change to the installation directory ---
cd "${{INSTALL_DIR}}" || {{ echo \"ERROR: Failed to cd to ${{INSTALL_DIR}}\"; exit 1; }}

# --- 2. Activate Virtual Environment ---
if [ ! -f "${{VENV_PATH}}" ]; then
  echo \"ERROR: Virtual environment not found at '${{VENV_PATH}}'.\" >&2
  echo \"Please run 'uv venv' in \"{install_dir}\".\" >&2
  exit 1
fi
source "${{VENV_PATH}}"

# --- 3. Set PLUGIN_MAGIC_COOKIE_VALUE from TF_PLUGIN_MAGIC_COOKIE environment variable ---
export PLUGIN_MAGIC_COOKIE_VALUE="$TF_PLUGIN_MAGIC_COOKIE"

# --- 4. Execute Provider ---
exec pyvider "$@"
"""

        atomic_write_text(target_provider_path, script_content)
        target_provider_path.chmod(target_provider_path.stat().st_mode | 0o111)

    except Exception as e:
        pout(
            f"An unexpected error occurred placing provider script: {e}",
            style="red",
            bold=True,
        )
        raise
